### PR TITLE
Remove QCD

### PR DESCRIPTION
**Pull request by MaximilianAlgehed**
This just nukes the stuff that's not necessary for djed in order to avoid a qcd dependency.

### CODE REVIEW

**Comment by etiennejf** [comment]
Seems OK as the modifications don't touch any sensible functionalities we are relying on. I'm doing some final checks before approving this PR. Thx.

**Review by etiennejf — CHANGES_REQUESTED** [review]
I'm getting this error when trying to compile this commit tag in my local djed repo.
`/work/iohk/stablecoin/git-repo/plutus-update/dist-newstyle/src/plutus-ap_-7c01e75cb2d7343c/plutus-use-cases: getDirectoryContents:openDirStream: does not exist (No such file or directory)`

**Comment by MaximilianAlgehed** [comment]
That looks like you have an old source repository stanza that points to subdirs that don't exist any more.

**Comment by MaximilianAlgehed** [comment]
Replace the `source-repository-stanza` with this:
```
-- Direct dependency.
source-repository-package
  type: git
  location: https://github.com/quviq/plutus-apps
  tag: f25718b47e6750a9b8da847fa833982eb7dd5836
  subdir:
    freer-extras
    pab-blockfrost
    playground-common
    plutus-contract
    plutus-chain-index-core
    plutus-chain-index
    plutus-ledger
    plutus-ledger-constraints
    plutus-pab
    plutus-script-utils
    rewindable-index
```
That's what I have in my version and it's working.

**Comment by etiennejf** [comment]
> Replace the `source-repository-stanza` with this:
> 
> ```
> -- Direct dependency.
> source-repository-package
>   type: git
>   location: https://github.com/quviq/plutus-apps
>   tag: f25718b47e6750a9b8da847fa833982eb7dd5836
>   subdir:
>     freer-extras
>     pab-blockfrost
>     playground-common
>     plutus-contract
>     plutus-chain-index-core
>     plutus-chain-index
>     plutus-ledger
>     plutus-ledger-constraints
>     plutus-pab
>     plutus-script-utils
>     rewindable-index
> ```
> 
> That's what I have in my version and it's working.

My fault !! I had to remove the deleted packages from cabal.project.

**Review by etiennejf — APPROVED** [review]
Thanks for the contribution .👏  I've tested it also on our PlutusV2 branch and everything is working perfectly fine. In the end we will only require the following packages from plutus-apps (as from PlutusV2):
```
freer-extras
plutus-chain-index-core
plutus-chain-index
plutus-ledger
plutus-script-utils
```

We will now be able to fully migrate all our test suites to the  new framework

**Pull request merged**
